<a href="https://www.kaggle.com/code/prantakumerpandit390/ats-score-prediction-project?scriptVersionId=346170242" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [68]:
import pandas as pd

train = pd.read_csv("/kaggle/input/datasets/prantakumerpandit390/ats-score/train.csv")
valid = pd.read_csv("/kaggle/input/datasets/prantakumerpandit390/ats-score/validation.csv")

In [69]:
train.sample(20)

,text,ats_score,original_label
4486,Professional SummaryBusiness Intelligence Cons...,24.7,No Fit
2497,SummaryObtain a challenging career in Informat...,85.6,Good Fit
1482,SummaryA business management graduate with sig...,51.1,Potential Fit
4492,Professional SummaryRELATED KNOWLEDGE AND SKIL...,50.5,Potential Fit
2656,Summary12 years of professional experience in ...,55.9,Potential Fit
4229,SummarySkilled and technically qualified Java ...,27.0,No Fit
1089,SummaryProficient Front End Developer effectiv...,27.8,No Fit
5016,Summary5 years of professional experience in M...,25.1,No Fit
789,Professional SummaryHighly regarded self-start...,25.6,No Fit
2265,SummarySeasoned Data Entry Operator with 5 yea...,24.9,No Fit
1618,Professional SummaryWith the attitude of learn...,87.3,Good Fit
340,"Professional SummaryAdept at managing budgets,...",52.0,Potential Fit
2233,SummaryHaving achieved a milestone of 7 years ...,50.1,Potential Fit
2452,SummaryTo obtain a position where my business ...,80.3,Good Fit
5014,SummaryTo utilize my customer relations and ma...,24.1,No Fit
2,SummaryHaving achieved a milestone of 7 years ...,53.9,Potential Fit
2056,SummaryLogical Data Analyst skilled in require...,22.3,No Fit
3095,"SummaryHighly organized, detail-oriented, and ...",81.3,Good Fit
4971,"ProfileLogical Data Analyst, skilled in elicit...",24.3,No Fit
4836,ProfileHighly motivated Sales Associate with e...,23.3,No Fit

In [70]:

#try foe split the resume and job discription


def split_resume_job(text):

    if " SEP " in text:

        resume, job = text.split(" SEP ", 1)

    else:

        resume = text
        job = ""

    return pd.Series([resume, job])

In [71]:
train[["resume","job_description"]] = train["text"].apply(split_resume_job)

valid[["resume","job_description"]] = valid["text"].apply(split_resume_job)

In [72]:
print(train.columns)

Index(['text', 'ats_score', 'original_label', 'resume', 'job_description'], dtype='object')

In [73]:
train.head()

,text,ats_score,original_label,resume,job_description
0,SummaryI am seeking a position wherein I may u...,80.6,Good Fit,SummaryI am seeking a position wherein I may u...,- Share resume to shan imrsoft.com Job Title ...
1,ProfileHighly motivated Sales Associate with e...,24.3,No Fit,ProfileHighly motivated Sales Associate with e...,Purpose StatementThe Software Engineering Man...
2,SummaryHaving achieved a milestone of 7 years ...,53.9,Potential Fit,SummaryHaving achieved a milestone of 7 years ...,"Title Business AnalystLocation Santa Clara, C..."
3,SummaryWireless communications engineer with e...,52.5,Potential Fit,SummaryWireless communications engineer with e...,Job Description As a Principal Software Engin...
4,SummaryData Entry experienced and adept at inp...,59.2,Potential Fit,SummaryData Entry experienced and adept at inp...,"Title Data EngineerLocation fully remote, how..."

In [74]:
train.isnull().sum()

text               0
ats_score          0
original_label     0
resume             0
job_description    0
dtype: int64

In [75]:
train.duplicated().sum()

np.int64(0)

In [76]:
#Cleaning data

import re

def clean_text(text):

    text = str(text)

    text = text.lower()

    text = re.sub(r"http\S+", "", text)

    text = re.sub(r"www\S+", "", text)

    text = re.sub(r"<.*?>", "", text)

    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)

    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [77]:
train.sample(5)

,text,ats_score,original_label,resume,job_description
3337,"SummaryI am a professional, experienced mechan...",28.8,No Fit,"SummaryI am a professional, experienced mechan...",Note By applying to this position you will ha...
4678,Summary5 years experience in development of We...,29.5,No Fit,Summary5 years experience in development of We...,Purpose StatementThe Software Engineering Man...
2192,SummaryHighly motivated Sales Associate with e...,51.1,Potential Fit,SummaryHighly motivated Sales Associate with e...,We are currently recruiting for a power elect...
4676,SummarySeasoned Electrical Engineer successful...,84.3,Good Fit,SummarySeasoned Electrical Engineer successful...,Our client is a growing Medical Device compan...
1763,Professional SummaryEnthusiastic computer engi...,51.4,Potential Fit,Professional SummaryEnthusiastic computer engi...,Immediate need 3-Month Contract to Hire- no C...

In [78]:
train["resume"] = train["resume"].apply(clean_text)
train["job_description"] = train["job_description"].apply(clean_text)

valid["resume"] = valid["resume"].apply(clean_text)
valid["job_description"] = valid["job_description"].apply(clean_text)

In [79]:
train.drop(columns=["text"], inplace=True)

valid.drop(columns=["text"], inplace=True)

In [80]:
import re

def preprocess_text(text):

    if pd.isna(text):
        return ""

    text = str(text)

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)

    # Remove HTML
    text = re.sub(r'<.*?>', ' ', text)

    # Add space between letters and numbers
    text = re.sub(r'([a-zA-Z])(\d)', r'\1 \2', text)
    text = re.sub(r'(\d)([a-zA-Z])', r'\1 \2', text)

    # Add space before capital letters in joined words
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)

    # Keep useful symbols
    text = re.sub(r'[^a-z0-9+#.\-\s]', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

In [81]:
train.sample(5)

,ats_score,original_label,resume,job_description
1819,25.6,No Fit,professional summaryelectrical engineer with t...,a remote contract senior accountant job headqu...
6,20.5,No Fit,summaryrecent graduate from nucamp coding boot...,centurion consulting group is looking for a so...
2277,81.6,Good Fit,professional summarysummary and skills skilled...,job description job title salesforce communica...
3219,84.0,Good Fit,career overviewseeking to secure a position in...,who we are apex fintech solutions afs powers i...
2070,87.7,Good Fit,summarycertified software development professi...,who we are apex fintech solutions afs powers i...

In [82]:
train["resume"] = train["resume"].apply(preprocess_text)
train["job_description"] = train["job_description"].apply(preprocess_text)

valid["resume"] = valid["resume"].apply(preprocess_text)
valid["job_description"] = valid["job_description"].apply(preprocess_text)

In [83]:
train[["resume","job_description"]].head()

,resume,job_description
0,summaryi am seeking a position wherein i may u...,share resume to shan imrsoft com job title jde...
1,profilehighly motivated sales associate with e...,purpose statementthe software engineering mana...
2,summaryhaving achieved a milestone of 7 years ...,title business analystlocation santa clara ca ...
3,summarywireless communications engineer with e...,job description as a principal software engine...
4,summarydata entry experienced and adept at inp...,title data engineerlocation fully remote howev...

In [84]:
train.head()
train.info()
print(train.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5099 entries, 0 to 5098
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ats_score        5099 non-null   float64
 1   original_label   5099 non-null   object
 2   resume           5099 non-null   object
 3   job_description  5099 non-null   object
dtypes: float64(1), object(3)
memory usage: 159.5+ KB
(5099, 4)

In [85]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (6.0.0)
Requirement already satisfied: transformers<6.0.0,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.16.1)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.23.1)
Requirement already satisfied: huggingface-hub<2.0.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=2.2 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.24.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.2->sentence-transformers) (1.5.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.2->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.2->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.1.2)

In [86]:
pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (6.0.0)
Requirement already satisfied: transformers<6.0.0,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.16.1)
Requirement already satisfied: tokenizers>=0.19 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.23.1)
Requirement already satisfied: huggingface-hub<2.0.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=2.2 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.24.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.24.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.2->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.2->sentence-transformers) (1.5.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=5.0.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.2->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.2->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0.0,>=1.3.0->sentence-transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [87]:
!pip list | grep -E "transformers|accelerate|sentence|torch"

accelerate                               1.13.0
pytorch-ignite                           0.5.4
pytorch-lightning                        2.6.5
sentence-transformers                    6.0.0
sentencepiece                            0.2.1
torch                                    2.10.0+cu128
torchao                                  0.10.0
torchaudio                               2.10.0+cu128
torchcodec                               0.10.0+cu128
torchdata                                0.11.0
torchinfo                                1.8.0
torchmetrics                             1.9.0
torchsummary                             1.5.1
torchtune                                0.6.1
torchvision                              0.25.0+cu128
transformers                             5.16.1

In [88]:
from sentence_transformers import SentenceTransformer

In [89]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [90]:
resume_embeddings = model.encode(
    train["resume"].tolist(),
    show_progress_bar=True,
    convert_to_numpy=True
)

Batches:   0%|          | 0/160 [00:00<?, ?it/s]

In [91]:
job_embeddings = model.encode(
    train["job_description"].tolist(),
    show_progress_bar=True,
    convert_to_numpy=True
)

Batches:   0%|          | 0/160 [00:00<?, ?it/s]

In [92]:
print("Resume Shape:", resume_embeddings.shape)
print("Job Shape:", job_embeddings.shape)

Resume Shape: (5099, 384)
Job Shape: (5099, 384)

In [93]:
import numpy as np

X = np.concatenate(
    (resume_embeddings, job_embeddings),
    axis=1
)

y = train["ats_score"].values

In [94]:
print("X Shape :", X.shape)
print("y Shape :", y.shape)

X Shape : (5099, 768)
y Shape : (5099,)

In [95]:
#Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [96]:
print(X_train.shape)
print(X_test.shape)

(4079, 768)
(1020, 768)

In [97]:
#KNN
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(
    n_neighbors=5
)

knn.fit(X_train,y_train)

KNeighborsRegressor()

In [98]:
knn_pred = knn.predict(X_test)

In [99]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import numpy as np

print("KNN")

print("MAE :",mean_absolute_error(y_test,knn_pred))

#print("RMSE :",np.sqrt(mean_squared_error(y_test,knn_pred)))

#print("R2 :",r2_score(y_test,knn_pred))

KNN
MAE : 17.379243137254903

In [100]:
#Random Forest

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [101]:
rf_pred = rf.predict(X_test)

In [102]:
print("Random Forest")

print("MAE :",mean_absolute_error(y_test,rf_pred))

#print("RMSE :",np.sqrt(mean_squared_error(y_test,rf_pred)))

#print("R2 :",r2_score(y_test,rf_pred))

Random Forest
MAE : 17.468379732726422

In [103]:
#X-GBoost

from xgboost import XGBRegressor

xgb = XGBRegressor(

    n_estimators=300,

    learning_rate=0.05,

    max_depth=6,

    random_state=42
)

xgb.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [104]:
xgb_pred = xgb.predict(X_test)

In [105]:
#Evo

print("XGBoost")

print("MAE :",mean_absolute_error(y_test,xgb_pred))

print("RMSE :",np.sqrt(mean_squared_error(y_test,xgb_pred)))

print("R2 :",r2_score(y_test,xgb_pred))

XGBoost
MAE : 15.434659916223262
RMSE : 18.896608176192768
R2 : 0.42867390931703575

In [106]:
#comparison 

import pandas as pd

results = pd.DataFrame({

    "Model":[
        "KNN",
        "Random Forest",
        "XGBoost"
    ],

    "MAE":[
        mean_absolute_error(y_test,knn_pred),
        mean_absolute_error(y_test,rf_pred),
        mean_absolute_error(y_test,xgb_pred)
    ],

    "RMSE":[
        np.sqrt(mean_squared_error(y_test,knn_pred)),
        np.sqrt(mean_squared_error(y_test,rf_pred)),
        np.sqrt(mean_squared_error(y_test,xgb_pred))
    ],

    "R2":[
        r2_score(y_test,knn_pred),
        r2_score(y_test,rf_pred),
        r2_score(y_test,xgb_pred)
    ]
})

results

           Model        MAE       RMSE        R2
0            KNN  17.379243  21.729263  0.244549
1  Random Forest  17.468380  19.978733  0.361366
2        XGBoost  15.434660  18.896608  0.428674

In [107]:
# Linear Regression

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

# Train model
lr.fit(X_train, y_train)

# Predict on test data
lr_pred = lr.predict(X_test)

# Evaluation
print("Linear Regression")

print("MAE :", mean_absolute_error(y_test, lr_pred))

print("RMSE :", np.sqrt(mean_squared_error(y_test, lr_pred)))

print("R2 :", r2_score(y_test, lr_pred))

Linear Regression
MAE : 18.863816317389993
RMSE : 23.092217428356232
R2 : 0.1468063442941352

In [108]:
# Compare all regression models

results = pd.DataFrame({

    "Model": [
        "KNN",
        "Random Forest",
        "XGBoost",
        "Linear Regression"
    ],

    "MAE": [
        mean_absolute_error(y_test, knn_pred),
        mean_absolute_error(y_test, rf_pred),
        mean_absolute_error(y_test, xgb_pred),
        mean_absolute_error(y_test, lr_pred)
    ],

    "RMSE": [
        np.sqrt(mean_squared_error(y_test, knn_pred)),
        np.sqrt(mean_squared_error(y_test, rf_pred)),
        np.sqrt(mean_squared_error(y_test, xgb_pred)),
        np.sqrt(mean_squared_error(y_test, lr_pred))
    ],

    "R2": [
        r2_score(y_test, knn_pred),
        r2_score(y_test, rf_pred),
        r2_score(y_test, xgb_pred),
        r2_score(y_test, lr_pred)
    ]
})

results

               Model        MAE       RMSE        R2
0                KNN  17.379243  21.729263  0.244549
1      Random Forest  17.468380  19.978733  0.361366
2            XGBoost  15.434660  18.896608  0.428674
3  Linear Regression  18.863816  23.092217  0.146806

In [109]:
# Sort models by RMSE: lower RMSE is better

results_sorted = results.sort_values(
    by="RMSE",
    ascending=True
).reset_index(drop=True)

results_sorted

               Model        MAE       RMSE        R2
0            XGBoost  15.434660  18.896608  0.428674
1      Random Forest  17.468380  19.978733  0.361366
2                KNN  17.379243  21.729263  0.244549
3  Linear Regression  18.863816  23.092217  0.146806

In [110]:
best_model = results_sorted.iloc[0]

print("Best Model :", best_model["Model"])
print("MAE :", best_model["MAE"])
print("RMSE :", best_model["RMSE"])
print("R2 :", best_model["R2"])

Best Model : XGBoost
MAE : 15.434659916223262
RMSE : 18.896608176192768
R2 : 0.42867390931703575

In [111]:
train.sample(5)

,ats_score,original_label,resume,job_description
3915,59.3,Potential Fit,professional summaryenergetic data engineer in...,calling all data nerds who love finance if you...
4894,56.0,Potential Fit,professional summaryenthusiastic computer engi...,are you passionate about the clean tech automo...
226,27.0,No Fit,career overviewdedicated personable and motiva...,position staff accountantoverview mississippi ...
711,56.8,Potential Fit,summaryhighly motivated sales associate with e...,position title senior accountant organization ...
1913,58.2,Potential Fit,summaryi am an accounting professional looking...,job purpose the senior accountant is responsib...

In [112]:
#K-Selection
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error

best_k = 0
best_mae = float("inf")

print("Validation Results")
print("-"*30)

for k in [1,3,5,7,9]:

    knn = KNeighborsRegressor(n_neighbors=k)

    knn.fit(X_train, y_train)

    pred = knn.predict(X_test)

    mae = mean_absolute_error(y_test, pred)

    print(f"k = {k}   MAE = {mae:.4f}")

    if mae < best_mae:
        best_mae = mae
        best_k = k

print("\nBest k =", best_k)
print("Best MAE =", best_mae)

Validation Results
------------------------------
k = 1   MAE = 18.3780
k = 3   MAE = 17.3167
k = 5   MAE = 17.3792
k = 7   MAE = 17.3048
k = 9   MAE = 17.6307

Best k = 7
Best MAE = 17.304788515406162

In [113]:
#train-test for K
final_model = KNeighborsRegressor(
    n_neighbors=best_k
)

final_model.fit(X_train, y_train)

y_pred = final_model.predict(X_test)

In [114]:
#prediction one resume
sample = X_test[0].reshape(1,-1)

prediction = final_model.predict(sample)

print("Predicted ATS Score :", prediction[0])

Predicted ATS Score : 50.32857142857142

In [115]:
#predictate multiple resume 

samples = X_test[:5]

predictions = final_model.predict(samples)

for i,pred in enumerate(predictions):

    print(f"Resume {i+1} ATS Score = {pred:.2f}")

Resume 1 ATS Score = 50.33
Resume 2 ATS Score = 25.60
Resume 3 ATS Score = 38.86
Resume 4 ATS Score = 45.83
Resume 5 ATS Score = 84.76

In [116]:
#weight knn

samples = X_test[:5]

predictions = final_model.predict(samples)

for i,pred in enumerate(predictions):

    print(f"Resume {i+1} ATS Score = {pred:.2f}")

Resume 1 ATS Score = 50.33
Resume 2 ATS Score = 25.60
Resume 3 ATS Score = 38.86
Resume 4 ATS Score = 45.83
Resume 5 ATS Score = 84.76

In [134]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor, BaggingRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score
from statistics import mean

kfold = KFold(
    n_splits=5,
    shuffle=True,
    random_state=32
)

# Store validation R²
results = {
    "Linear Regression": [],
    "KNN": [],
    "Random Forest": [],
    "XGBoost": [],
    "Bagging LR + KNN": []
}

fold = 1

for train_index, val_index in kfold.split(X):

    X_train_cv = X[train_index]
    X_val_cv = X[val_index]

    y_train_cv = y[train_index]
    y_val_cv = y[val_index]

    # =========================
    # Linear Regression
    # =========================

    lr = LinearRegression()

    lr.fit(X_train_cv, y_train_cv)

    lr_val_pred = lr.predict(X_val_cv)

    lr_val_r2 = r2_score(
        y_val_cv,
        lr_val_pred
    )

    results["Linear Regression"].append(lr_val_r2)


    # =========================
    # KNN
    # =========================

    knn = KNeighborsRegressor(
        n_neighbors=best_k
    )

    knn.fit(X_train_cv, y_train_cv)

    knn_val_pred = knn.predict(X_val_cv)

    knn_val_r2 = r2_score(
        y_val_cv,
        knn_val_pred
    )

    results["KNN"].append(knn_val_r2)


    # =========================
    # Random Forest
    # =========================

    rf = RandomForestRegressor(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    )

    rf.fit(X_train_cv, y_train_cv)

    rf_val_pred = rf.predict(X_val_cv)

    rf_val_r2 = r2_score(
        y_val_cv,
        rf_val_pred
    )

    results["Random Forest"].append(rf_val_r2)


    # =========================
    # XGBoost
    # =========================

    xgb = XGBRegressor(
        n_estimators=100,
        learning_rate=0.1,
        random_state=42,
        n_jobs=-1
    )

    xgb.fit(X_train_cv, y_train_cv)

    xgb_val_pred = xgb.predict(X_val_cv)

    xgb_val_r2 = r2_score(
        y_val_cv,
        xgb_val_pred
    )

    results["XGBoost"].append(xgb_val_r2)


    # =========================
    # Bagging Linear Regression
    # =========================

    bag_lr = BaggingRegressor(
        estimator=LinearRegression(),
        n_estimators=10,
        random_state=42,
        n_jobs=-1
    )

    bag_lr.fit(X_train_cv, y_train_cv)

    bag_lr_pred = bag_lr.predict(X_val_cv)


    # =========================
    # Bagging KNN
    # =========================

    bag_knn = BaggingRegressor(
        estimator=KNeighborsRegressor(
            n_neighbors=best_k
        ),
        n_estimators=10,
        random_state=42,
        n_jobs=-1
    )

    bag_knn.fit(X_train_cv, y_train_cv)

    bag_knn_pred = bag_knn.predict(X_val_cv)


    # Combine Bagging predictions
    bag_pred = (
        bag_lr_pred +
        bag_knn_pred
    ) / 2

    bag_r2 = r2_score(
        y_val_cv,
        bag_pred
    )

    results["Bagging LR + KNN"].append(bag_r2)


    # =========================
    # Print Fold Results
    # =========================

    print(f"\n========== Fold {fold} ==========")

    print("Linear Regression R² :", lr_val_r2)
    print("KNN R²               :", knn_val_r2)
    print("Random Forest R²     :", rf_val_r2)
    print("XGBoost R²           :", xgb_val_r2)
    print("Bagging LR + KNN R²  :", bag_r2)

    fold += 1


# =========================
# Average Validation R²
# =========================

print("\n\n======================================")
print("       5-FOLD VALIDATION RESULTS")
print("======================================")

for name, scores in results.items():

    print(f"\n{name}")
    print("Average Validation R² :", mean(scores))

========== Fold 1 ==========
Linear Regression R² : 0.10010695427842642
KNN R²               : 0.15678745371600855
Random Forest R²     : 0.3201673085143726
XGBoost R²           : 0.3460184167032254
Bagging LR + KNN R²  : 0.2168278303189084

========== Fold 2 ==========
Linear Regression R² : 0.20061073291572817
KNN R²               : 0.21468407791774802
Random Forest R²     : 0.36030879946442207
XGBoost R²           : 0.39557760268777364
Bagging LR + KNN R²  : 0.29030966610644016

========== Fold 3 ==========
Linear Regression R² : 0.11930157972446243
KNN R²               : 0.18643731648166173
Random Forest R²     : 0.31220185239895826
XGBoost R²           : 0.3572242565931143
Bagging LR + KNN R²  : 0.23168484570115244

========== Fold 4 ==========
Linear Regression R² : 0.09631774238100188
KNN R²               : 0.23381846721098043
Random Forest R²     : 0.35570609722949753
XGBoost R²           : 0.3934966902987804
Bagging LR + KNN R²  : 0.27258000150406514

========== Fold 5 ==========
Linear Regression R² : 0.10041021540898376
KNN R²               : 0.22427498629353704
Random Forest R²     : 0.34678301639855413
XGBoost R²           : 0.39609038276450326
Bagging LR + KNN R²  : 0.25125868166209


======================================
       5-FOLD VALIDATION RESULTS
======================================

Linear Regression
Average Validation R² : 0.12334944494172054

KNN
Average Validation R² : 0.20320046032398714

Random Forest
Average Validation R² : 0.3390334148011609

XGBoost
Average Validation R² : 0.3776814698094794

Bagging LR + KNN
Average Validation R² : 0.25253220505853125

In [135]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

# XGBoost
xgb_model = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(X_train, y_train)

# Predictions
xgb_train_pred = xgb_model.predict(X_train)
xgb_test_pred = xgb_model.predict(X_test)

# Metrics
print("XGBoost Final Model")
print("----------------------------")

print("Training R² :", r2_score(y_train, xgb_train_pred))
print("Test R²     :", r2_score(y_test, xgb_test_pred))

print("MAE         :", mean_absolute_error(y_test, xgb_test_pred))

print("RMSE        :", np.sqrt(
    mean_squared_error(y_test, xgb_test_pred)
))

XGBoost Final Model
----------------------------
Training R² : 0.8670265210907564
Test R²     : 0.3900365713140772
MAE         : 16.09559861134548
RMSE        : 19.525120723966214

In [136]:
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV

xgb = XGBRegressor(
    random_state=42,
    n_jobs=-1
)

param_grid = {
    "n_estimators": [50, 100, 150],
    "max_depth": [2, 3, 4],
    "learning_rate": [0.03, 0.05, 0.1],
    "subsample": [0.7, 0.8, 1.0],
    "colsample_bytree": [0.7, 0.8, 1.0]
}

search = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=param_grid,
    n_iter=8,
    scoring="r2",
    cv=5,
    random_state=42,
    n_jobs=-1
)

search.fit(X_train, y_train)

print("Best Parameters:")
print(search.best_params_)

print("\nBest 5-Fold CV R²:")
print(search.best_score_)

Best Parameters:
{'subsample': 0.8, 'n_estimators': 100, 'max_depth': 4, 'learning_rate': 0.1, 'colsample_bytree': 1.0}

Best 5-Fold CV R²:
0.2807579620502068

In [137]:
best_xgb = search.best_estimator_

best_xgb.fit(X_train, y_train)

train_pred = best_xgb.predict(X_train)
test_pred = best_xgb.predict(X_test)

print("Tuned XGBoost")
print("----------------------------")
print("Training R² :", r2_score(y_train, train_pred))
print("Test R²     :", r2_score(y_test, test_pred))
print("MAE         :", mean_absolute_error(y_test, test_pred))
print("RMSE        :", np.sqrt(mean_squared_error(y_test, test_pred)))

Tuned XGBoost
----------------------------
Training R² : 0.6367642624117567
Test R²     : 0.3420341485879044
MAE         : 17.109915493609858
RMSE        : 20.278858573245333

In [138]:
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

final_model = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42,
    n_jobs=-1
)

final_model.fit(X_train, y_train)

final_pred = final_model.predict(X_test)

print("FINAL XGBOOST MODEL")
print("----------------------------")
print("Test R² :", r2_score(y_test, final_pred))
print("MAE     :", mean_absolute_error(y_test, final_pred))
print("RMSE    :", np.sqrt(mean_squared_error(y_test, final_pred)))

FINAL XGBOOST MODEL
----------------------------
Test R² : 0.3900365713140772
MAE     : 16.09559861134548
RMSE    : 19.525120723966214

In [139]:
import joblib

joblib.dump(final_model, "ats_xgboost_model.pkl")

print("Model saved successfully.")

Model saved successfully.

In [140]:
import os

print(os.path.exists("/kaggle/working/ats_xgboost_model.pkl"))

True

In [141]:
import joblib
import os

path = "/kaggle/working/ats_xgboost_model.pkl"

print("Exists:", os.path.exists(path))
print("Size:", os.path.getsize(path) / 1024, "KB")

model = joblib.load(path)

print("Model type:", type(model))
print("Number of trees:", model.n_estimators)

Exists: True
Size: 373.0302734375 KB
Model type: <class 'xgboost.sklearn.XGBRegressor'>
Number of trees: 100

In [142]:
test_model = joblib.load("/kaggle/working/ats_xgboost_model.pkl")

test_prediction = test_model.predict(X_test)

print("Test R²:", r2_score(y_test, test_prediction))
print("MAE:", mean_absolute_error(y_test, test_prediction))
print("RMSE:", np.sqrt(mean_squared_error(y_test, test_prediction)))

Test R²: 0.3900365713140772
MAE: 16.09559861134548
RMSE: 19.525120723966214

In [145]:
from IPython.display import HTML

HTML("""
<a href="/kaggle/working/ats_xgboost_model.pkl"
   download="ats_xgboost_model.pkl">
   <button>Download XGBoost Model</button>
</a>
""")

In [146]:
import shutil
import os

source = "/kaggle/working/ats_xgboost_model.pkl"
zip_base = "/kaggle/working/ats_xgboost_model"

shutil.make_archive(
    zip_base,
    "zip",
    "/kaggle/working",
    "ats_xgboost_model.pkl"
)

print("ZIP exists:", os.path.exists("/kaggle/working/ats_xgboost_model.zip"))
print("ZIP size:", os.path.getsize("/kaggle/working/ats_xgboost_model.zip") / 1024, "KB")

ZIP exists: True
ZIP size: 116.46484375 KB

In [118]:

from sklearn.ensemble import BaggingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

# Bagging Linear Regression
bag_lr = BaggingRegressor(
    estimator=LinearRegression(),
    n_estimators=10,
    random_state=42,
    n_jobs=-1
)

# Bagging KNN
bag_knn = BaggingRegressor(
    estimator=KNeighborsRegressor(n_neighbors=best_k),
    n_estimators=10,
    random_state=42,
    n_jobs=-1
)

bag_lr.fit(X_train, y_train)
bag_knn.fit(X_train, y_train)

lr_pred = bag_lr.predict(X_test)
knn_pred = bag_knn.predict(X_test)

# Combine predictions by averaging
bag_pred = (lr_pred + knn_pred) / 2

print("Bagging Ensemble")
print("MAE :", mean_absolute_error(y_test, bag_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, bag_pred)))
print("R²  :", r2_score(y_test, bag_pred))

Bagging Ensemble
MAE : 17.44955824167598
RMSE: 21.11719063308946
R²  : 0.28650879781316874

In [119]:
#allready done bagging on knn and linear but still using random forest and xgboost as model but not for any bagging or  boosting .

from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score
from statistics import mean

kfold = KFold(
    n_splits=5,
    shuffle=True,
    random_state=32
)

models = {
    "Linear Regression": LinearRegression(),

    "KNN": KNeighborsRegressor(
        n_neighbors=best_k
    ),

    "Random Forest": RandomForestRegressor(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ),

    "XGBoost": XGBRegressor(
        n_estimators=200,
        learning_rate=0.1,
        random_state=42,
        n_jobs=-1
    )
}

results = {}

for name, model in models.items():

    train_r2_scores = []
    val_r2_scores = []

    for train_index, val_index in kfold.split(X):

        X_train_cv = X[train_index]
        X_val_cv = X[val_index]

        y_train_cv = y[train_index]
        y_val_cv = y[val_index]

        model.fit(X_train_cv, y_train_cv)

        train_pred = model.predict(X_train_cv)
        val_pred = model.predict(X_val_cv)

        train_r2_scores.append(
            r2_score(y_train_cv, train_pred)
        )

        val_r2_scores.append(
            r2_score(y_val_cv, val_pred)
        )

    avg_train_r2 = mean(train_r2_scores)
    avg_val_r2 = mean(val_r2_scores)

    results[name] = (avg_train_r2, avg_val_r2)

    print("\n", name)
    print("Average Training R²   :", avg_train_r2)
    print("Average Validation R² :", avg_val_r2)
    print("Train-Validation Gap  :", avg_train_r2 - avg_val_r2)

 Linear Regression
Average Training R²   : 0.42059598779440976
Average Validation R² : 0.12334944494172054
Train-Validation Gap  : 0.29724654285268926

 KNN
Average Training R²   : 0.43036971269684465
Average Validation R² : 0.22397969464025713
Train-Validation Gap  : 0.20639001805658752

 Random Forest
Average Training R²   : 0.9085285786579919
Average Validation R² : 0.34134687463419033
Train-Validation Gap  : 0.5671817040238015

 XGBoost
Average Training R²   : 0.9619579710542031
Average Validation R² : 0.393381824312296
Train-Validation Gap  : 0.568576146741907

In [133]:
#Stacking applying

from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

estimators = [
    ("lr", LinearRegression()),

    ("knn", KNeighborsRegressor(
        n_neighbors=best_k
    )),

    ("rf", RandomForestRegressor(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    )),

    ("xgb", XGBRegressor(
        n_estimators=100,
        learning_rate=0.1,
        random_state=42,
        n_jobs=-1
    ))
]

stack = StackingRegressor(
    estimators=estimators,
    final_estimator=LinearRegression(),
    cv=5,
    n_jobs=-1
)

stack.fit(X_train, y_train)

stack_pred = stack.predict(X_test)

print("Stacking Ensemble")
print("MAE  :", mean_absolute_error(y_test, stack_pred))
print("RMSE :", np.sqrt(mean_squared_error(y_test, stack_pred)))
print("R²   :", r2_score(y_test, stack_pred))

Stacking Ensemble
MAE  : 15.714465244209366
RMSE : 19.094224606585644
R²   : 0.416661829611491

In [120]:
#saving the  model
import joblib

bagging_models = {
    "bag_lr": bag_lr,
    "bag_knn": bag_knn
}

joblib.dump(
    bagging_models,
    "/kaggle/working/ats_bagging_models.pkl"
)

print("Bagging models saved successfully.")

Bagging models saved successfully.

In [121]:
#Loading the save bagging model

import joblib

bagging_models = joblib.load(
    "/kaggle/working/ats_bagging_models.pkl"
)

bag_lr = bagging_models["bag_lr"]
bag_knn = bagging_models["bag_knn"]

print("Bagging models loaded successfully.")

Bagging models loaded successfully.

In [122]:
#testing the loaded model

import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

lr_pred = bag_lr.predict(X_test)
knn_pred = bag_knn.predict(X_test)

y_pred = (lr_pred + knn_pred) / 2

print("Bagging Ensemble")
print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R²  :", r2_score(y_test, y_pred))

Bagging Ensemble
MAE : 17.44955824167598
RMSE: 21.11719063308946
R²  : 0.28650879781316874

In [123]:
!pip install -q -U sentence-transformers transformers

from sentence_transformers import SentenceTransformer

sbert_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [124]:
#using cleaning function 

import re
from bs4 import BeautifulSoup

def clean_text(text):

    text = str(text).lower()

    text = re.sub(r"http\S+|www\S+", " ", text)

    text = BeautifulSoup(text, "html.parser").get_text(" ")

    text = re.sub(r"\S+@\S+", " ", text)

    text = re.sub(r"\+?\d[\d\s().-]{7,}\d", " ", text)

    text = re.sub(r"\s+", " ", text).strip()

    return text

In [125]:
#ATS prediction creating function 
def predict_ats(resume, job_description):

    resume_clean = clean_text(resume)
    job_clean = clean_text(job_description)

    resume_embedding = sbert_model.encode(resume_clean)
    job_embedding = sbert_model.encode(job_clean)

    combined_features = np.concatenate([
        resume_embedding,
        job_embedding
    ])

    combined_features = combined_features.reshape(1, -1)

    lr_prediction = bag_lr.predict(combined_features)[0]
    knn_prediction = bag_knn.predict(combined_features)[0]

    ats_score = (lr_prediction + knn_prediction) / 2

    return float(ats_score)

In [126]:
print("X exists:", "X" in globals())
print("y exists:", "y" in globals())

X exists: True
y exists: True

In [127]:
print("train_df exists:", "train_df" in globals())
print("validation_df exists:", "validation_df" in globals())
print("resume_clean exists:", "resume_clean" in globals())
print("job_clean exists:", "job_clean" in globals())

train_df exists: False
validation_df exists: False
resume_clean exists: False
job_clean exists: False

In [128]:
best_k = 5

from sklearn.ensemble import BaggingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

bag_lr = BaggingRegressor(
    estimator=LinearRegression(),
    n_estimators=10,
    random_state=42,
    n_jobs=-1
)

bag_knn = BaggingRegressor(
    estimator=KNeighborsRegressor(n_neighbors=best_k),
    n_estimators=10,
    random_state=42,
    n_jobs=-1
)

bag_lr.fit(X_train, y_train)
bag_knn.fit(X_train, y_train)

print("Bagging models trained successfully.")

Bagging models trained successfully.

In [129]:
!pip install -q gradio

In [130]:
import numpy as np
import gradio as gr

interface = gr.Interface(
    fn=predict_ats,
    inputs=[
        gr.Textbox(
            lines=12,
            label="Resume",
            placeholder="Paste the resume here..."
        ),
        gr.Textbox(
            lines=12,
            label="Job Description",
            placeholder="Paste the job description here..."
        )
    ],
    outputs=gr.Number(
        label="Predicted ATS Score"
    ),
    title="ATS Score Prediction",
    description="Enter a resume and job description to predict the ATS score."
)

interface.launch(
    share=True,
    debug=True
)

* Running on local URL:  http://127.0.0.1:7861
* Running on public URL: https://1fad6dd7a5022d1a36.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7861 <> https://1fad6dd7a5022d1a36.gradio.live

In [131]:
print(type(bag_lr))
print(type(bag_knn))

<class 'sklearn.ensemble._bagging.BaggingRegressor'>
<class 'sklearn.ensemble._bagging.BaggingRegressor'>

In [132]:
import joblib
import os

bagging_models = {
    "bag_lr": bag_lr,
    "bag_knn": bag_knn
}

model_path = "/kaggle/working/ats_bagging_models.pkl"

joblib.dump(bagging_models, model_path)

print("Model saved:", os.path.exists(model_path))
print("Path:", model_path)

Model saved: True
Path: /kaggle/working/ats_bagging_models.pkl