<a href="https://www.kaggle.com/code/prantakumerpandit390/ats-score-prediction-project?scriptVersionId=338110419" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd

train = pd.read_csv("/kaggle/input/datasets/prantakumerpandit390/ats-score/train.csv")
valid = pd.read_csv("/kaggle/input/datasets/prantakumerpandit390/ats-score/validation.csv")

In [2]:
train.sample(20)

,text,ats_score,original_label
409,SummaryTo obtain an entry-level position as an...,83.30,Good Fit
2491,Professional SummaryHighly motivated Sales Ass...,88.90,Good Fit
2000,Professional SummaryProductive Data Entry Oper...,82.40,Good Fit
2944,SummaryHighly motivated Sales Associate with e...,20.80,No Fit
417,SummaryMotivated accounting professional focus...,53.30,Potential Fit
4565,SummaryQuality Assurance - Analyst9 years Tand...,50.50,Potential Fit
3131,Professional SummaryFinancial Accountant with ...,23.70,No Fit
4407,Career FocusI am a detail-oriented professiona...,56.50,Potential Fit
881,Professional SummaryExperienced Analyst seekin...,28.10,No Fit
3632,SummaryRecent graduate from Nucamp Coding Boot...,23.20,No Fit
3076,Summary11 20 1989 collaborative project manage...,24.50,No Fit
447,Professional SummarySeeking a position in an o...,24.40,No Fit
4574,"SummaryManager, Accountant, Project and Safety...",22.60,No Fit
746,"SummaryJessica, is highly skilled, accomplishe...",86.50,Good Fit
3275,SummaryEnergetic worker with a broad range of ...,25.90,No Fit
1476,Professional SummaryTo obtain a position as a ...,28.20,No Fit
3121,"ProfileSkilled, motivated and result-driven Q...",26.79,No Fit
3390,SummarySeeking an Accountant position that uti...,55.90,Potential Fit
348,Professional ProfileTo secure a position with ...,81.40,Good Fit
4024,Professional SummaryHighly motivated Sales Ass...,23.40,No Fit

In [3]:

#try foe split the resume and job discription


def split_resume_job(text):

    if " SEP " in text:

        resume, job = text.split(" SEP ", 1)

    else:

        resume = text
        job = ""

    return pd.Series([resume, job])

In [4]:
train[["resume","job_description"]] = train["text"].apply(split_resume_job)

valid[["resume","job_description"]] = valid["text"].apply(split_resume_job)

In [5]:
print(train.columns)

Index(['text', 'ats_score', 'original_label', 'resume', 'job_description'], dtype='object')

In [6]:
train.head()

,text,ats_score,original_label,resume,job_description
0,SummaryI am seeking a position wherein I may u...,80.6,Good Fit,SummaryI am seeking a position wherein I may u...,- Share resume to shan imrsoft.com Job Title ...
1,ProfileHighly motivated Sales Associate with e...,24.3,No Fit,ProfileHighly motivated Sales Associate with e...,Purpose StatementThe Software Engineering Man...
2,SummaryHaving achieved a milestone of 7 years ...,53.9,Potential Fit,SummaryHaving achieved a milestone of 7 years ...,"Title Business AnalystLocation Santa Clara, C..."
3,SummaryWireless communications engineer with e...,52.5,Potential Fit,SummaryWireless communications engineer with e...,Job Description As a Principal Software Engin...
4,SummaryData Entry experienced and adept at inp...,59.2,Potential Fit,SummaryData Entry experienced and adept at inp...,"Title Data EngineerLocation fully remote, how..."

In [7]:
train.isnull().sum()

text               0
ats_score          0
original_label     0
resume             0
job_description    0
dtype: int64

In [8]:
train.duplicated().sum()

np.int64(0)

In [9]:
#Cleaning data

import re

def clean_text(text):

    text = str(text)

    text = text.lower()

    text = re.sub(r"http\S+", "", text)

    text = re.sub(r"www\S+", "", text)

    text = re.sub(r"<.*?>", "", text)

    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)

    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [10]:
train.sample(5)

,text,ats_score,original_label,resume,job_description
1250,SummaryOver 5 years of engineering and finance...,58.5,Potential Fit,SummaryOver 5 years of engineering and finance...,"Direct Supply, Inc. is seeking a qualified ca..."
4003,Professional ProfileExpert in Functional Testi...,58.6,Potential Fit,Professional ProfileExpert in Functional Testi...,Lead Software Developer New York City - Hybri...
2576,SummaryCapable Accountant successful at managi...,84.8,Good Fit,SummaryCapable Accountant successful at managi...,"Job Title Senior AccountantLocation Atlanta, ..."
2291,SummaryResult-oriented software engineer with ...,24.7,No Fit,SummaryResult-oriented software engineer with ...,"Dexian, formerly Hunter Hollis is working wit..."
4726,SummaryHighly motivated Sales Associate with e...,27.7,No Fit,SummaryHighly motivated Sales Associate with e...,Kindly focus on the highlighted skill in the ...

In [11]:
train["resume"] = train["resume"].apply(clean_text)
train["job_description"] = train["job_description"].apply(clean_text)

valid["resume"] = valid["resume"].apply(clean_text)
valid["job_description"] = valid["job_description"].apply(clean_text)

In [12]:
train.drop(columns=["text"], inplace=True)

valid.drop(columns=["text"], inplace=True)

In [13]:
import re

def preprocess_text(text):

    if pd.isna(text):
        return ""

    text = str(text)

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)

    # Remove HTML
    text = re.sub(r'<.*?>', ' ', text)

    # Add space between letters and numbers
    text = re.sub(r'([a-zA-Z])(\d)', r'\1 \2', text)
    text = re.sub(r'(\d)([a-zA-Z])', r'\1 \2', text)

    # Add space before capital letters in joined words
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)

    # Keep useful symbols
    text = re.sub(r'[^a-z0-9+#.\-\s]', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

In [14]:
train.sample(5)

,ats_score,original_label,resume,job_description
695,89.20,Good Fit,summarysoftware engineer with 13 years program...,centurion consulting group is looking for a so...
4165,50.94,Potential Fit,each new employee is responsible for completin...,job description our mission is to redefine the...
1916,24.10,No Fit,summarysenior software engineer passionate abo...,calling all innovators find your future at fis...
1972,88.70,Good Fit,profilelogical data analyst skilled in eliciti...,rolegaming business analystresponsibilities ab...
3852,52.50,Potential Fit,summaryfull stack software engineer with 8 yea...,are you passionate about the clean tech automo...

In [15]:
train["resume"] = train["resume"].apply(preprocess_text)
train["job_description"] = train["job_description"].apply(preprocess_text)

valid["resume"] = valid["resume"].apply(preprocess_text)
valid["job_description"] = valid["job_description"].apply(preprocess_text)

In [16]:
train[["resume","job_description"]].head()

,resume,job_description
0,summaryi am seeking a position wherein i may u...,share resume to shan imrsoft com job title jde...
1,profilehighly motivated sales associate with e...,purpose statementthe software engineering mana...
2,summaryhaving achieved a milestone of 7 years ...,title business analystlocation santa clara ca ...
3,summarywireless communications engineer with e...,job description as a principal software engine...
4,summarydata entry experienced and adept at inp...,title data engineerlocation fully remote howev...

In [17]:
train.head()
train.info()
print(train.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5099 entries, 0 to 5098
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ats_score        5099 non-null   float64
 1   original_label   5099 non-null   object
 2   resume           5099 non-null   object
 3   job_description  5099 non-null   object
dtypes: float64(1), object(3)
memory usage: 159.5+ KB
(5099, 4)

In [18]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

In [19]:
pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [20]:
from sentence_transformers import SentenceTransformer

In [21]:
model = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [22]:
resume_embeddings = model.encode(
    train["resume"].tolist(),
    show_progress_bar=True,
    convert_to_numpy=True
)

Batches:   0%|          | 0/160 [00:00<?, ?it/s]

In [23]:
job_embeddings = model.encode(
    train["job_description"].tolist(),
    show_progress_bar=True,
    convert_to_numpy=True
)

Batches:   0%|          | 0/160 [00:00<?, ?it/s]

In [24]:
print("Resume Shape:", resume_embeddings.shape)
print("Job Shape:", job_embeddings.shape)

Resume Shape: (5099, 384)
Job Shape: (5099, 384)

In [25]:
import numpy as np

X = np.concatenate(
    (resume_embeddings, job_embeddings),
    axis=1
)

y = train["ats_score"].values

In [26]:
print("X Shape :", X.shape)
print("y Shape :", y.shape)

X Shape : (5099, 768)
y Shape : (5099,)

In [27]:
#Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [28]:
print(X_train.shape)
print(X_test.shape)

(4079, 768)
(1020, 768)

In [29]:
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(
    n_neighbors=5
)

knn.fit(X_train,y_train)

KNeighborsRegressor()

In [30]:
knn_pred = knn.predict(X_test)

In [31]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import numpy as np

print("KNN")

print("MAE :",mean_absolute_error(y_test,knn_pred))

print("RMSE :",np.sqrt(mean_squared_error(y_test,knn_pred)))

print("R2 :",r2_score(y_test,knn_pred))

KNN
MAE : 17.379376470588234
RMSE : 21.72954672636623
R2 : 0.24452921266780325

In [32]:
#Random Forest

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train,y_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [33]:
rf_pred = rf.predict(X_test)

In [34]:
print("Random Forest")

print("MAE :",mean_absolute_error(y_test,rf_pred))

print("RMSE :",np.sqrt(mean_squared_error(y_test,rf_pred)))

print("R2 :",r2_score(y_test,rf_pred))

Random Forest
MAE : 17.480122045051356
RMSE : 19.99777363469934
R2 : 0.36014784421804535

In [35]:
#X-GBoost

from xgboost import XGBRegressor

xgb = XGBRegressor(

    n_estimators=300,

    learning_rate=0.05,

    max_depth=6,

    random_state=42
)

xgb.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [36]:
xgb_pred = xgb.predict(X_test)

In [37]:
#Evo

print("XGBoost")

print("MAE :",mean_absolute_error(y_test,xgb_pred))

print("RMSE :",np.sqrt(mean_squared_error(y_test,xgb_pred)))

print("R2 :",r2_score(y_test,xgb_pred))

XGBoost
MAE : 15.45215517762128
RMSE : 18.899967492878684
R2 : 0.4284707579526309

In [38]:
#comparison 

import pandas as pd

results = pd.DataFrame({

    "Model":[
        "KNN",
        "Random Forest",
        "XGBoost"
    ],

    "MAE":[
        mean_absolute_error(y_test,knn_pred),
        mean_absolute_error(y_test,rf_pred),
        mean_absolute_error(y_test,xgb_pred)
    ],

    "RMSE":[
        np.sqrt(mean_squared_error(y_test,knn_pred)),
        np.sqrt(mean_squared_error(y_test,rf_pred)),
        np.sqrt(mean_squared_error(y_test,xgb_pred))
    ],

    "R2":[
        r2_score(y_test,knn_pred),
        r2_score(y_test,rf_pred),
        r2_score(y_test,xgb_pred)
    ]
})

results

           Model        MAE       RMSE        R2
0            KNN  17.379376  21.729547  0.244529
1  Random Forest  17.480122  19.997774  0.360148
2        XGBoost  15.452155  18.899967  0.428471