<a href="https://www.kaggle.com/code/prantakumerpandit390/ats-score-prediction-project?scriptVersionId=343494199" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd

train = pd.read_csv("/kaggle/input/datasets/prantakumerpandit390/ats-score/train.csv")
valid = pd.read_csv("/kaggle/input/datasets/prantakumerpandit390/ats-score/validation.csv")

In [2]:
train.sample(20)

,text,ats_score,original_label
3319,Professional SummaryExperienced Analyst seekin...,81.2,Good Fit
89,SummarySeasoned Data Architect adept at unders...,23.4,No Fit
1896,SummaryData Entry experienced and adept at inp...,28.3,No Fit
2810,SummaryCreative and innovative Engineer with e...,22.2,No Fit
1298,SummaryISTQB certified QA Test Analyst Payment...,23.8,No Fit
4843,SummaryQuality Assurance - Analyst9 years Tand...,52.1,Potential Fit
30,SummaryDiligent and driven Analyst who has ach...,54.1,Potential Fit
4596,SummaryFull stack software engineer specializi...,89.0,Good Fit
2061,Professional ProfileSeeking for a challenging ...,81.5,Good Fit
4206,"Professional SummaryProactive, performance-dri...",27.1,No Fit
3474,Professional SummaryBusiness Intelligence Cons...,24.7,No Fit
4889,SummaryQuality-focused accounting professional...,58.4,Potential Fit
767,SummaryObtain a challenging career in Informat...,89.4,Good Fit
4428,SummarySkilled in high profile account managem...,86.7,Good Fit
4705,SummaryA position in a company that will utili...,20.6,No Fit
1010,"Professional SummaryHighly analytical, results...",52.0,Potential Fit
3072,SummarySeasoned Data Entry Operator with 5 yea...,81.4,Good Fit
1612,SummaryInnovative Accountant proficient in ext...,50.5,Potential Fit
2009,SummaryHistory of Professional planning and Or...,55.2,Potential Fit
4515,SummaryHighly motivated Sales Associate with e...,26.9,No Fit

In [3]:

#try foe split the resume and job discription


def split_resume_job(text):

    if " SEP " in text:

        resume, job = text.split(" SEP ", 1)

    else:

        resume = text
        job = ""

    return pd.Series([resume, job])

In [4]:
train[["resume","job_description"]] = train["text"].apply(split_resume_job)

valid[["resume","job_description"]] = valid["text"].apply(split_resume_job)

In [5]:
print(train.columns)

Index(['text', 'ats_score', 'original_label', 'resume', 'job_description'], dtype='object')

In [6]:
train.head()

,text,ats_score,original_label,resume,job_description
0,SummaryI am seeking a position wherein I may u...,80.6,Good Fit,SummaryI am seeking a position wherein I may u...,- Share resume to shan imrsoft.com Job Title ...
1,ProfileHighly motivated Sales Associate with e...,24.3,No Fit,ProfileHighly motivated Sales Associate with e...,Purpose StatementThe Software Engineering Man...
2,SummaryHaving achieved a milestone of 7 years ...,53.9,Potential Fit,SummaryHaving achieved a milestone of 7 years ...,"Title Business AnalystLocation Santa Clara, C..."
3,SummaryWireless communications engineer with e...,52.5,Potential Fit,SummaryWireless communications engineer with e...,Job Description As a Principal Software Engin...
4,SummaryData Entry experienced and adept at inp...,59.2,Potential Fit,SummaryData Entry experienced and adept at inp...,"Title Data EngineerLocation fully remote, how..."

In [7]:
train.isnull().sum()

text               0
ats_score          0
original_label     0
resume             0
job_description    0
dtype: int64

In [8]:
train.duplicated().sum()

np.int64(0)

In [9]:
#Cleaning data

import re

def clean_text(text):

    text = str(text)

    text = text.lower()

    text = re.sub(r"http\S+", "", text)

    text = re.sub(r"www\S+", "", text)

    text = re.sub(r"<.*?>", "", text)

    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)

    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [10]:
train.sample(5)

,text,ats_score,original_label,resume,job_description
5083,Career OverviewNetwork security professional ...,84.82,Good Fit,Career OverviewNetwork security professional ...,Who We Are Apex Fintech Solutions (AFS) power...
851,Professional SummaryEnthusiastic computer engi...,88.30,Good Fit,Professional SummaryEnthusiastic computer engi...,Rightware is the company behind the Kanzi fam...
3664,SummaryHighly motivated Sales Associate with e...,59.60,Potential Fit,SummaryHighly motivated Sales Associate with e...,Position Title Senior Accountant Organization...
615,SummaryPursue a challenging and rewarding posi...,52.30,Potential Fit,SummaryPursue a challenging and rewarding posi...,( Candidates without any Visa Constraints) ( ...
4693,"Professional SummaryDependable, results-driven...",21.10,No Fit,"Professional SummaryDependable, results-driven...","About UsAt Pacific Science Engineering, were ..."

In [11]:
train["resume"] = train["resume"].apply(clean_text)
train["job_description"] = train["job_description"].apply(clean_text)

valid["resume"] = valid["resume"].apply(clean_text)
valid["job_description"] = valid["job_description"].apply(clean_text)

In [12]:
train.drop(columns=["text"], inplace=True)

valid.drop(columns=["text"], inplace=True)

In [13]:
import re

def preprocess_text(text):

    if pd.isna(text):
        return ""

    text = str(text)

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)

    # Remove HTML
    text = re.sub(r'<.*?>', ' ', text)

    # Add space between letters and numbers
    text = re.sub(r'([a-zA-Z])(\d)', r'\1 \2', text)
    text = re.sub(r'(\d)([a-zA-Z])', r'\1 \2', text)

    # Add space before capital letters in joined words
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)

    # Keep useful symbols
    text = re.sub(r'[^a-z0-9+#.\-\s]', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

In [14]:
train.sample(5)

,ats_score,original_label,resume,job_description
4727,59.9,Potential Fit,professional summaryqa test analyst developmen...,the company wizeline is a global digital servi...
1313,22.4,No Fit,summarydata protection consultant with 10 year...,hi my name is kartik jaiswal and i am a staffi...
55,58.9,Potential Fit,profilei am seeking to work in a interesting a...,perform and generate reports on all routine te...
2682,88.5,Good Fit,professional summarymotivated senior software ...,who we are multi media llc is a technology com...
1155,25.8,No Fit,professional summaryhighly regarded self start...,rightware is the company behind the kanzi fami...

In [15]:
train["resume"] = train["resume"].apply(preprocess_text)
train["job_description"] = train["job_description"].apply(preprocess_text)

valid["resume"] = valid["resume"].apply(preprocess_text)
valid["job_description"] = valid["job_description"].apply(preprocess_text)

In [16]:
train[["resume","job_description"]].head()

,resume,job_description
0,summaryi am seeking a position wherein i may u...,share resume to shan imrsoft com job title jde...
1,profilehighly motivated sales associate with e...,purpose statementthe software engineering mana...
2,summaryhaving achieved a milestone of 7 years ...,title business analystlocation santa clara ca ...
3,summarywireless communications engineer with e...,job description as a principal software engine...
4,summarydata entry experienced and adept at inp...,title data engineerlocation fully remote howev...

In [17]:
train.head()
train.info()
print(train.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5099 entries, 0 to 5098
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ats_score        5099 non-null   float64
 1   original_label   5099 non-null   object
 2   resume           5099 non-null   object
 3   job_description  5099 non-null   object
dtypes: float64(1), object(3)
memory usage: 159.5+ KB
(5099, 4)

In [18]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.5.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

In [19]:
pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.5.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [20]:
!pip list | grep -E "transformers|accelerate|sentence|torch"

accelerate                               1.13.0
pytorch-ignite                           0.5.4
pytorch-lightning                        2.6.5
sentence-transformers                    5.4.1
sentencepiece                            0.2.1
torch                                    2.10.0+cu128
torchao                                  0.10.0
torchaudio                               2.10.0+cu128
torchcodec                               0.10.0+cu128
torchdata                                0.11.0
torchinfo                                1.8.0
torchmetrics                             1.9.0
torchsummary                             1.5.1
torchtune                                0.6.1
torchvision                              0.25.0+cu128
transformers                             5.0.0

In [21]:
from sentence_transformers import SentenceTransformer

In [22]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [23]:
resume_embeddings = model.encode(
    train["resume"].tolist(),
    show_progress_bar=True,
    convert_to_numpy=True
)

Batches:   0%|          | 0/160 [00:00<?, ?it/s]

In [24]:
job_embeddings = model.encode(
    train["job_description"].tolist(),
    show_progress_bar=True,
    convert_to_numpy=True
)

Batches:   0%|          | 0/160 [00:00<?, ?it/s]

In [25]:
print("Resume Shape:", resume_embeddings.shape)
print("Job Shape:", job_embeddings.shape)

Resume Shape: (5099, 384)
Job Shape: (5099, 384)

In [26]:
import numpy as np

X = np.concatenate(
    (resume_embeddings, job_embeddings),
    axis=1
)

y = train["ats_score"].values

In [27]:
print("X Shape :", X.shape)
print("y Shape :", y.shape)

X Shape : (5099, 768)
y Shape : (5099,)

In [28]:
#Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [29]:
print(X_train.shape)
print(X_test.shape)

(4079, 768)
(1020, 768)

In [30]:
#KNN
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(
    n_neighbors=5
)

knn.fit(X_train,y_train)

KNeighborsRegressor()

In [31]:
knn_pred = knn.predict(X_test)

In [32]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import numpy as np

print("KNN")

print("MAE :",mean_absolute_error(y_test,knn_pred))

#print("RMSE :",np.sqrt(mean_squared_error(y_test,knn_pred)))

#print("R2 :",r2_score(y_test,knn_pred))

KNN
MAE : 17.379243137254903

In [33]:
#Random Forest

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [34]:
rf_pred = rf.predict(X_test)

In [35]:
print("Random Forest")

print("MAE :",mean_absolute_error(y_test,rf_pred))

#print("RMSE :",np.sqrt(mean_squared_error(y_test,rf_pred)))

#print("R2 :",r2_score(y_test,rf_pred))

Random Forest
MAE : 17.468379732726422

In [36]:
#X-GBoost

from xgboost import XGBRegressor

xgb = XGBRegressor(

    n_estimators=300,

    learning_rate=0.05,

    max_depth=6,

    random_state=42
)

xgb.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [37]:
xgb_pred = xgb.predict(X_test)

In [38]:
#Evo

print("XGBoost")

print("MAE :",mean_absolute_error(y_test,xgb_pred))

print("RMSE :",np.sqrt(mean_squared_error(y_test,xgb_pred)))

print("R2 :",r2_score(y_test,xgb_pred))

XGBoost
MAE : 15.434659916223262
RMSE : 18.896608176192768
R2 : 0.42867390931703575

In [39]:
#comparison 

import pandas as pd

results = pd.DataFrame({

    "Model":[
        "KNN",
        "Random Forest",
        "XGBoost"
    ],

    "MAE":[
        mean_absolute_error(y_test,knn_pred),
        mean_absolute_error(y_test,rf_pred),
        mean_absolute_error(y_test,xgb_pred)
    ],

    "RMSE":[
        np.sqrt(mean_squared_error(y_test,knn_pred)),
        np.sqrt(mean_squared_error(y_test,rf_pred)),
        np.sqrt(mean_squared_error(y_test,xgb_pred))
    ],

    "R2":[
        r2_score(y_test,knn_pred),
        r2_score(y_test,rf_pred),
        r2_score(y_test,xgb_pred)
    ]
})

results

           Model        MAE       RMSE        R2
0            KNN  17.379243  21.729263  0.244549
1  Random Forest  17.468380  19.978733  0.361366
2        XGBoost  15.434660  18.896608  0.428674

In [40]:
# Linear Regression

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

# Train model
lr.fit(X_train, y_train)

# Predict on test data
lr_pred = lr.predict(X_test)

# Evaluation
print("Linear Regression")

print("MAE :", mean_absolute_error(y_test, lr_pred))

print("RMSE :", np.sqrt(mean_squared_error(y_test, lr_pred)))

print("R2 :", r2_score(y_test, lr_pred))

Linear Regression
MAE : 18.863816317389993
RMSE : 23.092217428356232
R2 : 0.1468063442941352

In [41]:
# Compare all regression models

results = pd.DataFrame({

    "Model": [
        "KNN",
        "Random Forest",
        "XGBoost",
        "Linear Regression"
    ],

    "MAE": [
        mean_absolute_error(y_test, knn_pred),
        mean_absolute_error(y_test, rf_pred),
        mean_absolute_error(y_test, xgb_pred),
        mean_absolute_error(y_test, lr_pred)
    ],

    "RMSE": [
        np.sqrt(mean_squared_error(y_test, knn_pred)),
        np.sqrt(mean_squared_error(y_test, rf_pred)),
        np.sqrt(mean_squared_error(y_test, xgb_pred)),
        np.sqrt(mean_squared_error(y_test, lr_pred))
    ],

    "R2": [
        r2_score(y_test, knn_pred),
        r2_score(y_test, rf_pred),
        r2_score(y_test, xgb_pred),
        r2_score(y_test, lr_pred)
    ]
})

results

               Model        MAE       RMSE        R2
0                KNN  17.379243  21.729263  0.244549
1      Random Forest  17.468380  19.978733  0.361366
2            XGBoost  15.434660  18.896608  0.428674
3  Linear Regression  18.863816  23.092217  0.146806

In [42]:
# Sort models by RMSE: lower RMSE is better

results_sorted = results.sort_values(
    by="RMSE",
    ascending=True
).reset_index(drop=True)

results_sorted

               Model        MAE       RMSE        R2
0            XGBoost  15.434660  18.896608  0.428674
1      Random Forest  17.468380  19.978733  0.361366
2                KNN  17.379243  21.729263  0.244549
3  Linear Regression  18.863816  23.092217  0.146806

In [43]:
best_model = results_sorted.iloc[0]

print("Best Model :", best_model["Model"])
print("MAE :", best_model["MAE"])
print("RMSE :", best_model["RMSE"])
print("R2 :", best_model["R2"])

Best Model : XGBoost
MAE : 15.434659916223262
RMSE : 18.896608176192768
R2 : 0.42867390931703575

In [44]:
train.sample(5)

,ats_score,original_label,resume,job_description
668,24.0,No Fit,professional summaryexperienced data entry adm...,who we are apex fintech solutions afs powers i...
2173,28.4,No Fit,summarycontact detail oriented professional wi...,r 371317 comcast business offers technology so...
4637,88.2,Good Fit,summaryhighly motivated sales associate with e...,role senior software engineer type full time a...
2211,28.8,No Fit,summarysenior software engineer with 13 years ...,job description essential duties and responsib...
2272,83.3,Good Fit,summaryproactive bi developer data analyst wit...,a little about this gig agility partners is se...

In [45]:
#K-Selection
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error

best_k = 0
best_mae = float("inf")

print("Validation Results")
print("-"*30)

for k in [1,3,5,7,9]:

    knn = KNeighborsRegressor(n_neighbors=k)

    knn.fit(X_train, y_train)

    pred = knn.predict(X_test)

    mae = mean_absolute_error(y_test, pred)

    print(f"k = {k}   MAE = {mae:.4f}")

    if mae < best_mae:
        best_mae = mae
        best_k = k

print("\nBest k =", best_k)
print("Best MAE =", best_mae)

Validation Results
------------------------------
k = 1   MAE = 18.3780
k = 3   MAE = 17.3167
k = 5   MAE = 17.3792
k = 7   MAE = 17.3048
k = 9   MAE = 17.6307

Best k = 7
Best MAE = 17.304788515406162

In [46]:
#train-test for K
final_model = KNeighborsRegressor(
    n_neighbors=best_k
)

final_model.fit(X_train, y_train)

y_pred = final_model.predict(X_test)

In [47]:
#prediction one resume
sample = X_test[0].reshape(1,-1)

prediction = final_model.predict(sample)

print("Predicted ATS Score :", prediction[0])

Predicted ATS Score : 50.32857142857142

In [48]:
#predictate multiple resume 

samples = X_test[:5]

predictions = final_model.predict(samples)

for i,pred in enumerate(predictions):

    print(f"Resume {i+1} ATS Score = {pred:.2f}")

Resume 1 ATS Score = 50.33
Resume 2 ATS Score = 25.60
Resume 3 ATS Score = 38.86
Resume 4 ATS Score = 45.83
Resume 5 ATS Score = 84.76

In [49]:
#weight knn

samples = X_test[:5]

predictions = final_model.predict(samples)

for i,pred in enumerate(predictions):

    print(f"Resume {i+1} ATS Score = {pred:.2f}")

Resume 1 ATS Score = 50.33
Resume 2 ATS Score = 25.60
Resume 3 ATS Score = 38.86
Resume 4 ATS Score = 45.83
Resume 5 ATS Score = 84.76

In [50]:
from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score
from statistics import mean

kfold = KFold(
    n_splits=5,
    shuffle=True,
    random_state=32
)

# Store R² scores
lr_train_r2 = []
lr_val_r2 = []

knn_train_r2 = []
knn_val_r2 = []

fold = 1

for train_index, val_index in kfold.split(X):

    X_train_cv = X[train_index]
    X_val_cv = X[val_index]

    y_train_cv = y[train_index]
    y_val_cv = y[val_index]

    # =========================
    # Linear Regression
    # =========================

    lr = LinearRegression()

    lr.fit(X_train_cv, y_train_cv)

    lr_train_pred = lr.predict(X_train_cv)
    lr_val_pred = lr.predict(X_val_cv)

    lr_train_score = r2_score(y_train_cv, lr_train_pred)
    lr_val_score = r2_score(y_val_cv, lr_val_pred)

    lr_train_r2.append(lr_train_score)
    lr_val_r2.append(lr_val_score)


    # =========================
    # KNN Regression
    # =========================

    knn = KNeighborsRegressor(
        n_neighbors=best_k
    )

    knn.fit(X_train_cv, y_train_cv)

    knn_train_pred = knn.predict(X_train_cv)
    knn_val_pred = knn.predict(X_val_cv)

    knn_train_score = r2_score(y_train_cv, knn_train_pred)
    knn_val_score = r2_score(y_val_cv, knn_val_pred)

    knn_train_r2.append(knn_train_score)
    knn_val_r2.append(knn_val_score)


    print(f"\n========== Fold {fold} ==========")

    print("Linear Regression")
    print("Training R²   :", lr_train_score)
    print("Validation R² :", lr_val_score)

    print("\nKNN Regressor")
    print("Training R²   :", knn_train_score)
    print("Validation R² :", knn_val_score)

    fold += 1


# =========================
# Average Results
# =========================

print("\n\n======================================")
print("       AVERAGE TRAIN vs VALIDATION")
print("======================================")

print("\nLinear Regression")
print("Average Training R²   :", mean(lr_train_r2))
print("Average Validation R² :", mean(lr_val_r2))
print("R² Gap                :", mean(lr_train_r2) - mean(lr_val_r2))


print("\nKNN Regressor")
print("Average Training R²   :", mean(knn_train_r2))
print("Average Validation R² :", mean(knn_val_r2))
print("R² Gap                :", mean(knn_train_r2) - mean(knn_val_r2))

========== Fold 1 ==========
Linear Regression
Training R²   : 0.42841109560635215
Validation R² : 0.10010695427842642

KNN Regressor
Training R²   : 0.42959972738043894
Validation R² : 0.2006020403427442

========== Fold 2 ==========
Linear Regression
Training R²   : 0.4066676863683175
Validation R² : 0.20061073291572817

KNN Regressor
Training R²   : 0.4282555300112687
Validation R² : 0.2156316438824818

========== Fold 3 ==========
Linear Regression
Training R²   : 0.42288723365285774
Validation R² : 0.11930157972446243

KNN Regressor
Training R²   : 0.4461232061980438
Validation R² : 0.20390079493583502

========== Fold 4 ==========
Linear Regression
Training R²   : 0.4237466631271293
Validation R² : 0.09631774238100188

KNN Regressor
Training R²   : 0.4251670386861054
Validation R² : 0.2554462838894369

========== Fold 5 ==========
Linear Regression
Training R²   : 0.42126726021739225
Validation R² : 0.10041021540898376

KNN Regressor
Training R²   : 0.42270306120836654
Validation R² : 0.24431771015078774


======================================
       AVERAGE TRAIN vs VALIDATION
======================================

Linear Regression
Average Training R²   : 0.42059598779440976
Average Validation R² : 0.12334944494172054
R² Gap                : 0.29724654285268926

KNN Regressor
Average Training R²   : 0.43036971269684465
Average Validation R² : 0.22397969464025713
R² Gap                : 0.20639001805658752

In [51]:

from sklearn.ensemble import BaggingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

# Bagging Linear Regression
bag_lr = BaggingRegressor(
    estimator=LinearRegression(),
    n_estimators=10,
    random_state=42,
    n_jobs=-1
)

# Bagging KNN
bag_knn = BaggingRegressor(
    estimator=KNeighborsRegressor(n_neighbors=best_k),
    n_estimators=10,
    random_state=42,
    n_jobs=-1
)

bag_lr.fit(X_train, y_train)
bag_knn.fit(X_train, y_train)

lr_pred = bag_lr.predict(X_test)
knn_pred = bag_knn.predict(X_test)

# Combine predictions by averaging
bag_pred = (lr_pred + knn_pred) / 2

print("Bagging Ensemble")
print("MAE :", mean_absolute_error(y_test, bag_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, bag_pred)))
print("R²  :", r2_score(y_test, bag_pred))

Bagging Ensemble
MAE : 17.44955824167598
RMSE: 21.11719063308946
R²  : 0.28650879781316874

In [52]:
#allready done bagging on knn and linear but still using random forest and xgboost as model but not for any bagging or  boosting .

from sklearn.model_selection import KFold
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score
from statistics import mean

kfold = KFold(
    n_splits=5,
    shuffle=True,
    random_state=32
)

models = {
    "Linear Regression": LinearRegression(),

    "KNN": KNeighborsRegressor(
        n_neighbors=best_k
    ),

    "Random Forest": RandomForestRegressor(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ),

    "XGBoost": XGBRegressor(
        n_estimators=200,
        learning_rate=0.1,
        random_state=42,
        n_jobs=-1
    )
}

results = {}

for name, model in models.items():

    train_r2_scores = []
    val_r2_scores = []

    for train_index, val_index in kfold.split(X):

        X_train_cv = X[train_index]
        X_val_cv = X[val_index]

        y_train_cv = y[train_index]
        y_val_cv = y[val_index]

        model.fit(X_train_cv, y_train_cv)

        train_pred = model.predict(X_train_cv)
        val_pred = model.predict(X_val_cv)

        train_r2_scores.append(
            r2_score(y_train_cv, train_pred)
        )

        val_r2_scores.append(
            r2_score(y_val_cv, val_pred)
        )

    avg_train_r2 = mean(train_r2_scores)
    avg_val_r2 = mean(val_r2_scores)

    results[name] = (avg_train_r2, avg_val_r2)

    print("\n", name)
    print("Average Training R²   :", avg_train_r2)
    print("Average Validation R² :", avg_val_r2)
    print("Train-Validation Gap  :", avg_train_r2 - avg_val_r2)

 Linear Regression
Average Training R²   : 0.42059598779440976
Average Validation R² : 0.12334944494172054
Train-Validation Gap  : 0.29724654285268926

 KNN
Average Training R²   : 0.43036971269684465
Average Validation R² : 0.22397969464025713
Train-Validation Gap  : 0.20639001805658752

 Random Forest
Average Training R²   : 0.9085285786579919
Average Validation R² : 0.3413468746341903
Train-Validation Gap  : 0.5671817040238016

 XGBoost
Average Training R²   : 0.9619579710542031
Average Validation R² : 0.393381824312296
Train-Validation Gap  : 0.568576146741907

In [53]:
#saving the  model
import joblib

bagging_models = {
    "bag_lr": bag_lr,
    "bag_knn": bag_knn
}

joblib.dump(
    bagging_models,
    "/kaggle/working/ats_bagging_models.pkl"
)

print("Bagging models saved successfully.")

Bagging models saved successfully.

In [54]:
#Loading the save bagging model

import joblib

bagging_models = joblib.load(
    "/kaggle/working/ats_bagging_models.pkl"
)

bag_lr = bagging_models["bag_lr"]
bag_knn = bagging_models["bag_knn"]

print("Bagging models loaded successfully.")

Bagging models loaded successfully.

In [55]:
#testing the loaded model

import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

lr_pred = bag_lr.predict(X_test)
knn_pred = bag_knn.predict(X_test)

y_pred = (lr_pred + knn_pred) / 2

print("Bagging Ensemble")
print("MAE :", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R²  :", r2_score(y_test, y_pred))

Bagging Ensemble
MAE : 17.44955824167598
RMSE: 21.11719063308946
R²  : 0.28650879781316874

In [56]:
!pip install -q -U sentence-transformers transformers

from sentence_transformers import SentenceTransformer

sbert_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 739.6/739.6 kB 36.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 100.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 516.0/516.0 kB 34.3 MB/s eta 0:00:00

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [57]:
#using cleaning function 

import re
from bs4 import BeautifulSoup

def clean_text(text):

    text = str(text).lower()

    text = re.sub(r"http\S+|www\S+", " ", text)

    text = BeautifulSoup(text, "html.parser").get_text(" ")

    text = re.sub(r"\S+@\S+", " ", text)

    text = re.sub(r"\+?\d[\d\s().-]{7,}\d", " ", text)

    text = re.sub(r"\s+", " ", text).strip()

    return text

In [58]:
#ATS prediction creating function 
def predict_ats(resume, job_description):

    resume_clean = clean_text(resume)
    job_clean = clean_text(job_description)

    resume_embedding = sbert_model.encode(resume_clean)
    job_embedding = sbert_model.encode(job_clean)

    combined_features = np.concatenate([
        resume_embedding,
        job_embedding
    ])

    combined_features = combined_features.reshape(1, -1)

    lr_prediction = bag_lr.predict(combined_features)[0]
    knn_prediction = bag_knn.predict(combined_features)[0]

    ats_score = (lr_prediction + knn_prediction) / 2

    return float(ats_score)

In [59]:
print("X exists:", "X" in globals())
print("y exists:", "y" in globals())

X exists: True
y exists: True

In [60]:
print("train_df exists:", "train_df" in globals())
print("validation_df exists:", "validation_df" in globals())
print("resume_clean exists:", "resume_clean" in globals())
print("job_clean exists:", "job_clean" in globals())

train_df exists: False
validation_df exists: False
resume_clean exists: False
job_clean exists: False

In [61]:
best_k = 5

from sklearn.ensemble import BaggingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

bag_lr = BaggingRegressor(
    estimator=LinearRegression(),
    n_estimators=10,
    random_state=42,
    n_jobs=-1
)

bag_knn = BaggingRegressor(
    estimator=KNeighborsRegressor(n_neighbors=best_k),
    n_estimators=10,
    random_state=42,
    n_jobs=-1
)

bag_lr.fit(X_train, y_train)
bag_knn.fit(X_train, y_train)

print("Bagging models trained successfully.")

Bagging models trained successfully.

In [62]:
!pip install -q gradio

In [63]:
#creating gradio interface

import numpy as np

import gradio as gr

interface = gr.Interface(
    fn=predict_ats,
    inputs=[
        gr.Textbox(
            lines=12,
            label="Resume",
            placeholder="Paste the resume here..."
        ),
        gr.Textbox(
            lines=12,
            label="Job Description",
            placeholder="Paste the job description here..."
        )
    ],
    outputs=gr.Number(
        label="Predicted ATS Score"
    ),
    title="ATS Score Prediction",
    description="Enter a resume and job description to predict the ATS score."
)

interface.launch()

* Running on local URL:  http://127.0.0.1:7860
It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

* Running on public URL: https://1c6be39c5a24164896.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)