<a href="https://www.kaggle.com/code/prantakumerpandit390/ats-score-prediction-project?scriptVersionId=340677849" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd

train = pd.read_csv("/kaggle/input/datasets/prantakumerpandit390/ats-score/train.csv")
valid = pd.read_csv("/kaggle/input/datasets/prantakumerpandit390/ats-score/validation.csv")

In [2]:
train.sample(20)

,text,ats_score,original_label
1103,Professional SummaryCurrently working with Cat...,55.8,Potential Fit
874,SummaryPursue a challenging and rewarding posi...,25.8,No Fit
5089,Summary2 years experience in developing portal...,21.9,No Fit
1500,SummaryQuality-focused Data Entry Clerk experi...,20.3,No Fit
148,"Career OverviewDedicated, personable, and moti...",24.1,No Fit
760,Professional SummaryI am a design engineer wit...,23.0,No Fit
1899,Career OverviewExperienced Data Analyst with e...,55.6,Potential Fit
252,SUMMARYI am a full-stack developer with excell...,52.8,Potential Fit
3979,Professional SummaryTo obtain a full time oppo...,29.7,No Fit
564,SummaryTo obtain a position where my business ...,20.9,No Fit
4761,Summary IT Professional with over 8 years expe...,21.2,No Fit
2488,ProfileSoftware Test Engineer with two years o...,50.1,Potential Fit
4280,SummaryDetail oriented with strong skills in r...,26.2,No Fit
2974,SummaryExperienced Senior Accountant with over...,83.6,Good Fit
4063,Professional SummaryQA TEST ANALYST DEVELOPMEN...,81.8,Good Fit
1572,Professional SummaryExperienced Data Analyst c...,23.1,No Fit
139,SummaryVersatile professional looking to trans...,80.9,Good Fit
4889,SummaryQuality-focused accounting professional...,58.4,Potential Fit
394,Professional SummaryTo achieve a responsible p...,22.2,No Fit
1162,Career OverviewHighly accomplished Data Archit...,25.3,No Fit

In [3]:

#try foe split the resume and job discription


def split_resume_job(text):

    if " SEP " in text:

        resume, job = text.split(" SEP ", 1)

    else:

        resume = text
        job = ""

    return pd.Series([resume, job])

In [4]:
train[["resume","job_description"]] = train["text"].apply(split_resume_job)

valid[["resume","job_description"]] = valid["text"].apply(split_resume_job)

In [5]:
print(train.columns)

Index(['text', 'ats_score', 'original_label', 'resume', 'job_description'], dtype='object')

In [6]:
train.head()

,text,ats_score,original_label,resume,job_description
0,SummaryI am seeking a position wherein I may u...,80.6,Good Fit,SummaryI am seeking a position wherein I may u...,- Share resume to shan imrsoft.com Job Title ...
1,ProfileHighly motivated Sales Associate with e...,24.3,No Fit,ProfileHighly motivated Sales Associate with e...,Purpose StatementThe Software Engineering Man...
2,SummaryHaving achieved a milestone of 7 years ...,53.9,Potential Fit,SummaryHaving achieved a milestone of 7 years ...,"Title Business AnalystLocation Santa Clara, C..."
3,SummaryWireless communications engineer with e...,52.5,Potential Fit,SummaryWireless communications engineer with e...,Job Description As a Principal Software Engin...
4,SummaryData Entry experienced and adept at inp...,59.2,Potential Fit,SummaryData Entry experienced and adept at inp...,"Title Data EngineerLocation fully remote, how..."

In [7]:
train.isnull().sum()

text               0
ats_score          0
original_label     0
resume             0
job_description    0
dtype: int64

In [8]:
train.duplicated().sum()

np.int64(0)

In [9]:
#Cleaning data

import re

def clean_text(text):

    text = str(text)

    text = text.lower()

    text = re.sub(r"http\S+", "", text)

    text = re.sub(r"www\S+", "", text)

    text = re.sub(r"<.*?>", "", text)

    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)

    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [10]:
train.sample(5)

,text,ats_score,original_label,resume,job_description
2232,Career OverviewExpert level user interface fro...,50.8,Potential Fit,Career OverviewExpert level user interface fro...,- Share resume to shan imrsoft.com Job Title ...
3581,Professional SummaryEnthusiastic computer engi...,82.4,Good Fit,Professional SummaryEnthusiastic computer engi...,Senior Software EngineerSelby Jennings is par...
1418,"ProfileLogical Data Analyst, skilled in elicit...",23.4,No Fit,"ProfileLogical Data Analyst, skilled in elicit...",( Candidates without any Visa Constraints) ( ...
4491,Professional SummaryEnthusiastic computer engi...,87.5,Good Fit,Professional SummaryEnthusiastic computer engi...,Skills - Cucumber BDD Selenium UI Automation ...
26,SummaryISTQB certified QA Test Analyst Payment...,26.9,No Fit,SummaryISTQB certified QA Test Analyst Payment...,Calling all innovators find your future at Fi...

In [11]:
train["resume"] = train["resume"].apply(clean_text)
train["job_description"] = train["job_description"].apply(clean_text)

valid["resume"] = valid["resume"].apply(clean_text)
valid["job_description"] = valid["job_description"].apply(clean_text)

In [12]:
train.drop(columns=["text"], inplace=True)

valid.drop(columns=["text"], inplace=True)

In [13]:
import re

def preprocess_text(text):

    if pd.isna(text):
        return ""

    text = str(text)

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)

    # Remove HTML
    text = re.sub(r'<.*?>', ' ', text)

    # Add space between letters and numbers
    text = re.sub(r'([a-zA-Z])(\d)', r'\1 \2', text)
    text = re.sub(r'(\d)([a-zA-Z])', r'\1 \2', text)

    # Add space before capital letters in joined words
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)

    # Keep useful symbols
    text = re.sub(r'[^a-z0-9+#.\-\s]', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

In [14]:
train.sample(5)

,ats_score,original_label,resume,job_description
2949,50.4,Potential Fit,experience11 2017tocurrentbusiness analyst dat...,provides analysis to different functions such ...
159,83.5,Good Fit,career focusaccomplished and results oriented ...,about allvue we are allvue systems the leading...
1709,20.7,No Fit,summaryhighly motivated sales associate with e...,our client is a growing medical device company...
4005,26.2,No Fit,experienceelectrical engineer 11 2017tocurrent...,when you join verizon verizon is one of the wo...
4806,24.7,No Fit,summarydynamic and motivated it professional w...,lead software developer new york city hybrid 1...

In [15]:
train["resume"] = train["resume"].apply(preprocess_text)
train["job_description"] = train["job_description"].apply(preprocess_text)

valid["resume"] = valid["resume"].apply(preprocess_text)
valid["job_description"] = valid["job_description"].apply(preprocess_text)

In [16]:
train[["resume","job_description"]].head()

,resume,job_description
0,summaryi am seeking a position wherein i may u...,share resume to shan imrsoft com job title jde...
1,profilehighly motivated sales associate with e...,purpose statementthe software engineering mana...
2,summaryhaving achieved a milestone of 7 years ...,title business analystlocation santa clara ca ...
3,summarywireless communications engineer with e...,job description as a principal software engine...
4,summarydata entry experienced and adept at inp...,title data engineerlocation fully remote howev...

In [17]:
train.head()
train.info()
print(train.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5099 entries, 0 to 5098
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ats_score        5099 non-null   float64
 1   original_label   5099 non-null   object
 2   resume           5099 non-null   object
 3   job_description  5099 non-null   object
dtypes: float64(1), object(3)
memory usage: 159.5+ KB
(5099, 4)

In [18]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.5.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

In [19]:
pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cu128)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.11.0->sentence-transformers) (1.5.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [20]:
!pip list | grep -E "transformers|accelerate|sentence|torch"

accelerate                               1.13.0
pytorch-ignite                           0.5.4
pytorch-lightning                        2.6.5
sentence-transformers                    5.4.1
sentencepiece                            0.2.1
torch                                    2.10.0+cu128
torchao                                  0.10.0
torchaudio                               2.10.0+cu128
torchcodec                               0.10.0+cu128
torchdata                                0.11.0
torchinfo                                1.8.0
torchmetrics                             1.9.0
torchsummary                             1.5.1
torchtune                                0.6.1
torchvision                              0.25.0+cu128
transformers                             5.0.0

In [21]:
from sentence_transformers import SentenceTransformer

In [22]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [23]:
resume_embeddings = model.encode(
    train["resume"].tolist(),
    show_progress_bar=True,
    convert_to_numpy=True
)

Batches:   0%|          | 0/160 [00:00<?, ?it/s]

In [24]:
job_embeddings = model.encode(
    train["job_description"].tolist(),
    show_progress_bar=True,
    convert_to_numpy=True
)

Batches:   0%|          | 0/160 [00:00<?, ?it/s]

In [25]:
print("Resume Shape:", resume_embeddings.shape)
print("Job Shape:", job_embeddings.shape)

Resume Shape: (5099, 384)
Job Shape: (5099, 384)

In [26]:
import numpy as np

X = np.concatenate(
    (resume_embeddings, job_embeddings),
    axis=1
)

y = train["ats_score"].values

In [27]:
print("X Shape :", X.shape)
print("y Shape :", y.shape)

X Shape : (5099, 768)
y Shape : (5099,)

In [28]:
#Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [29]:
print(X_train.shape)
print(X_test.shape)

(4079, 768)
(1020, 768)

In [30]:
#KNN
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(
    n_neighbors=5
)

knn.fit(X_train,y_train)

KNeighborsRegressor()

In [31]:
knn_pred = knn.predict(X_test)

In [32]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
import numpy as np

print("KNN")

print("MAE :",mean_absolute_error(y_test,knn_pred))

#print("RMSE :",np.sqrt(mean_squared_error(y_test,knn_pred)))

#print("R2 :",r2_score(y_test,knn_pred))

KNN
MAE : 17.379243137254903

In [33]:
#Random Forest

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train,y_train)

RandomForestRegressor(random_state=42)

In [34]:
rf_pred = rf.predict(X_test)

In [35]:
print("Random Forest")

print("MAE :",mean_absolute_error(y_test,rf_pred))

#print("RMSE :",np.sqrt(mean_squared_error(y_test,rf_pred)))

#print("R2 :",r2_score(y_test,rf_pred))

Random Forest
MAE : 17.468379732726422

In [36]:
#X-GBoost

from xgboost import XGBRegressor

xgb = XGBRegressor(

    n_estimators=300,

    learning_rate=0.05,

    max_depth=6,

    random_state=42
)

xgb.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [37]:
xgb_pred = xgb.predict(X_test)

In [38]:
#Evo

print("XGBoost")

print("MAE :",mean_absolute_error(y_test,xgb_pred))

print("RMSE :",np.sqrt(mean_squared_error(y_test,xgb_pred)))

print("R2 :",r2_score(y_test,xgb_pred))

XGBoost
MAE : 15.434659916223262
RMSE : 18.896608176192768
R2 : 0.42867390931703575

In [39]:
#comparison 

import pandas as pd

results = pd.DataFrame({

    "Model":[
        "KNN",
        "Random Forest",
        "XGBoost"
    ],

    "MAE":[
        mean_absolute_error(y_test,knn_pred),
        mean_absolute_error(y_test,rf_pred),
        mean_absolute_error(y_test,xgb_pred)
    ],

    "RMSE":[
        np.sqrt(mean_squared_error(y_test,knn_pred)),
        np.sqrt(mean_squared_error(y_test,rf_pred)),
        np.sqrt(mean_squared_error(y_test,xgb_pred))
    ],

    "R2":[
        r2_score(y_test,knn_pred),
        r2_score(y_test,rf_pred),
        r2_score(y_test,xgb_pred)
    ]
})

results

           Model        MAE       RMSE        R2
0            KNN  17.379243  21.729263  0.244549
1  Random Forest  17.468380  19.978733  0.361366
2        XGBoost  15.434660  18.896608  0.428674

In [40]:
# Linear Regression

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

# Train model
lr.fit(X_train, y_train)

# Predict on test data
lr_pred = lr.predict(X_test)

# Evaluation
print("Linear Regression")

print("MAE :", mean_absolute_error(y_test, lr_pred))

print("RMSE :", np.sqrt(mean_squared_error(y_test, lr_pred)))

print("R2 :", r2_score(y_test, lr_pred))

Linear Regression
MAE : 18.863816317389993
RMSE : 23.092217428356232
R2 : 0.1468063442941352

In [41]:
# Compare all regression models

results = pd.DataFrame({

    "Model": [
        "KNN",
        "Random Forest",
        "XGBoost",
        "Linear Regression"
    ],

    "MAE": [
        mean_absolute_error(y_test, knn_pred),
        mean_absolute_error(y_test, rf_pred),
        mean_absolute_error(y_test, xgb_pred),
        mean_absolute_error(y_test, lr_pred)
    ],

    "RMSE": [
        np.sqrt(mean_squared_error(y_test, knn_pred)),
        np.sqrt(mean_squared_error(y_test, rf_pred)),
        np.sqrt(mean_squared_error(y_test, xgb_pred)),
        np.sqrt(mean_squared_error(y_test, lr_pred))
    ],

    "R2": [
        r2_score(y_test, knn_pred),
        r2_score(y_test, rf_pred),
        r2_score(y_test, xgb_pred),
        r2_score(y_test, lr_pred)
    ]
})

results

               Model        MAE       RMSE        R2
0                KNN  17.379243  21.729263  0.244549
1      Random Forest  17.468380  19.978733  0.361366
2            XGBoost  15.434660  18.896608  0.428674
3  Linear Regression  18.863816  23.092217  0.146806

In [42]:
# Sort models by RMSE: lower RMSE is better

results_sorted = results.sort_values(
    by="RMSE",
    ascending=True
).reset_index(drop=True)

results_sorted

               Model        MAE       RMSE        R2
0            XGBoost  15.434660  18.896608  0.428674
1      Random Forest  17.468380  19.978733  0.361366
2                KNN  17.379243  21.729263  0.244549
3  Linear Regression  18.863816  23.092217  0.146806

In [43]:
best_model = results_sorted.iloc[0]

print("Best Model :", best_model["Model"])
print("MAE :", best_model["MAE"])
print("RMSE :", best_model["RMSE"])
print("R2 :", best_model["R2"])

Best Model : XGBoost
MAE : 15.434659916223262
RMSE : 18.896608176192768
R2 : 0.42867390931703575

In [44]:
train.sample(5)

,ats_score,original_label,resume,job_description
4928,80.6,Good Fit,summary 8 years of accomplished experience in ...,job title senior accountantlocation atlanta ga...
3395,89.1,Good Fit,professional profileclaire 6 1 csa from pegasy...,reality labs at meta is building products that...
947,82.5,Good Fit,summaryproactive bi developer data analyst wit...,rolegaming business analystresponsibilities ab...
1238,20.6,No Fit,summaryhighly motivated sales associate with e...,job description our mission is to redefine the...
1002,57.5,Potential Fit,summarymanager accountant project and safety m...,job descriptionseeking a seasoned accountant w...

In [45]:
#K-Selection
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error

best_k = 0
best_mae = float("inf")

print("Validation Results")
print("-"*30)

for k in [1,3,5,7,9]:

    knn = KNeighborsRegressor(n_neighbors=k)

    knn.fit(X_train, y_train)

    pred = knn.predict(X_test)

    mae = mean_absolute_error(y_test, pred)

    print(f"k = {k}   MAE = {mae:.4f}")

    if mae < best_mae:
        best_mae = mae
        best_k = k

print("\nBest k =", best_k)
print("Best MAE =", best_mae)

Validation Results
------------------------------
k = 1   MAE = 18.3780
k = 3   MAE = 17.3167
k = 5   MAE = 17.3792
k = 7   MAE = 17.3048
k = 9   MAE = 17.6307

Best k = 7
Best MAE = 17.304788515406162

In [46]:
#train-test for K
final_model = KNeighborsRegressor(
    n_neighbors=best_k
)

final_model.fit(X_train, y_train)

y_pred = final_model.predict(X_test)

In [47]:
#prediction one resume
sample = X_test[0].reshape(1,-1)

prediction = final_model.predict(sample)

print("Predicted ATS Score :", prediction[0])

Predicted ATS Score : 50.32857142857142

In [48]:
#predictate multiple resume 

samples = X_test[:5]

predictions = final_model.predict(samples)

for i,pred in enumerate(predictions):

    print(f"Resume {i+1} ATS Score = {pred:.2f}")

Resume 1 ATS Score = 50.33
Resume 2 ATS Score = 25.60
Resume 3 ATS Score = 38.86
Resume 4 ATS Score = 45.83
Resume 5 ATS Score = 84.76

In [49]:
#weight knn

samples = X_test[:5]

predictions = final_model.predict(samples)

for i,pred in enumerate(predictions):

    print(f"Resume {i+1} ATS Score = {pred:.2f}")

Resume 1 ATS Score = 50.33
Resume 2 ATS Score = 25.60
Resume 3 ATS Score = 38.86
Resume 4 ATS Score = 45.83
Resume 5 ATS Score = 84.76

In [50]:
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from statistics import mean
import numpy as np

kfold = KFold(
    n_splits=5,
    shuffle=True,
    random_state=32
)

mae_scores = []
rmse_scores = []
r2_scores = []

fold = 1

for train_index, test_index in kfold.split(X):

    X_train_cv = X[train_index]
    X_test_cv = X[test_index]

    y_train_cv = y[train_index]
    y_test_cv = y[test_index]

    model = KNeighborsRegressor(
        n_neighbors=best_k
    )

    model.fit(X_train_cv, y_train_cv)

    pred = model.predict(X_test_cv)

    mae = mean_absolute_error(y_test_cv, pred)
    rmse = np.sqrt(mean_squared_error(y_test_cv, pred))
    r2 = r2_score(y_test_cv, pred)

    mae_scores.append(mae)
    rmse_scores.append(rmse)
    r2_scores.append(r2)

    print(f"\nFold {fold}")
    print("MAE :", mae)
    print("RMSE :", rmse)
    print("R² :", r2)

    fold += 1

print("\n========== Cross Validation Results ==========")
print("Average MAE :", mean(mae_scores))
print("Average RMSE:", mean(rmse_scores))
print("Average R² :", mean(r2_scores))

Fold 1
MAE : 18.166747899159663
RMSE : 22.108729462168842
R² : 0.2006020403427442

Fold 2
MAE : 17.76479411764706
RMSE : 22.063415802199447
R² : 0.2156316438824818

Fold 3
MAE : 18.2601918767507
RMSE : 22.585308026357712
R² : 0.20390079493583502

Fold 4
MAE : 17.301687675070028
RMSE : 21.510456590669936
R² : 0.2554462838894369

Fold 5
MAE : 18.005267068554605
RMSE : 21.652843775590465
R² : 0.24431771015078774

========== Cross Validation Results ==========
Average MAE : 17.89973772743641
Average RMSE: 21.984150731397282
Average R² : 0.22397969464025713

In [52]:
#Stacking applying as ensembel learning 


from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor



estimators = [

    ("lr", LinearRegression()),

    ("knn", KNeighborsRegressor(
        n_neighbors=best_k
    )),

    ("rf", RandomForestRegressor(
        n_estimators=200,
        random_state=42
    )),

    ("xgb", XGBRegressor(
        n_estimators=200,
        learning_rate=0.1,
        random_state=42
    ))

]


stack = StackingRegressor(
    estimators=estimators,
    final_estimator=LinearRegression(),
    cv=5,
    n_jobs=-1
)


stack.fit(X_train, y_train)


stack_pred = stack.predict(X_test)

print("Stacking Regressor")

print("MAE :", mean_absolute_error(y_test, stack_pred))
print("RMSE :", np.sqrt(mean_squared_error(y_test, stack_pred)))
print("R² :", r2_score(y_test, stack_pred))

Stacking Regressor
MAE : 15.281193972253284
RMSE : 18.836784311635956
R² : 0.43228565081312653