<a href="https://www.kaggle.com/code/prantakumerpandit390/ats-score-prediction-project?scriptVersionId=335935317" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import pandas as pd

train = pd.read_csv("/kaggle/input/datasets/prantakumerpandit390/ats-score/train.csv")
valid = pd.read_csv("/kaggle/input/datasets/prantakumerpandit390/ats-score/validation.csv")

In [2]:
train.sample(20)

,text,ats_score,original_label
3909,SummaryTo obtain a challenging position in the...,24.4,No Fit
136,SummaryRecent graduate from Nucamp Coding Boot...,26.9,No Fit
4261,Professional SummaryHighly skilled software de...,89.3,Good Fit
3103,"SummaryExperienced software engineer, and hand...",21.3,No Fit
431,SummaryA passionate researcher and learner wit...,89.5,Good Fit
310,Professional SummaryHighly regarded self-start...,22.1,No Fit
4471,"Professional SummaryAdept at managing budgets,...",27.3,No Fit
3702,Professional SummaryBusiness Intelligence Cons...,57.6,Potential Fit
741,SummaryObtain a challenging career in Informat...,29.8,No Fit
135,Professional ProfileHighly skilled professiona...,80.3,Good Fit
3829,SummaryHighly-motivated employee with desire t...,23.5,No Fit
1946,SummaryTo obtain a challenging position in the...,26.7,No Fit
4297,Professional SummaryOver 7 years of progressiv...,21.5,No Fit
3637,Career OverviewA position to lead diverse team...,81.4,Good Fit
3847,SummaryHighly motivated Sales Associate with e...,80.5,Good Fit
1912,SummaryDetail oriented with strong skills in r...,55.2,Potential Fit
1746,ProfileExperienced Corporate and Software Prof...,20.1,No Fit
4107,Professional SummaryWith the attitude of learn...,20.1,No Fit
1358,QUALIFICATIONS Over two years experience of da...,25.5,No Fit
129,"Professional SummaryFemale, 29 years old, Newl...",80.7,Good Fit

In [3]:

#try foe split the resume and job discription


def split_resume_job(text):

    if " SEP " in text:

        resume, job = text.split(" SEP ", 1)

    else:

        resume = text
        job = ""

    return pd.Series([resume, job])

In [4]:
train[["resume","job_description"]] = train["text"].apply(split_resume_job)

valid[["resume","job_description"]] = valid["text"].apply(split_resume_job)

In [5]:
print(train.columns)

Index(['text', 'ats_score', 'original_label', 'resume', 'job_description'], dtype='object')

In [6]:
train.head()

,text,ats_score,original_label,resume,job_description
0,SummaryI am seeking a position wherein I may u...,80.6,Good Fit,SummaryI am seeking a position wherein I may u...,- Share resume to shan imrsoft.com Job Title ...
1,ProfileHighly motivated Sales Associate with e...,24.3,No Fit,ProfileHighly motivated Sales Associate with e...,Purpose StatementThe Software Engineering Man...
2,SummaryHaving achieved a milestone of 7 years ...,53.9,Potential Fit,SummaryHaving achieved a milestone of 7 years ...,"Title Business AnalystLocation Santa Clara, C..."
3,SummaryWireless communications engineer with e...,52.5,Potential Fit,SummaryWireless communications engineer with e...,Job Description As a Principal Software Engin...
4,SummaryData Entry experienced and adept at inp...,59.2,Potential Fit,SummaryData Entry experienced and adept at inp...,"Title Data EngineerLocation fully remote, how..."

In [7]:
train.isnull().sum()

text               0
ats_score          0
original_label     0
resume             0
job_description    0
dtype: int64

In [8]:
train.duplicated().sum()

np.int64(0)

In [9]:
#Cleaning data

import re

def clean_text(text):

    text = str(text)

    text = text.lower()

    text = re.sub(r"http\S+", "", text)

    text = re.sub(r"www\S+", "", text)

    text = re.sub(r"<.*?>", "", text)

    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)

    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [10]:
train.sample(5)

,text,ats_score,original_label,resume,job_description
1581,Professional SummarySeeking Challenging and Re...,27.20,No Fit,Professional SummarySeeking Challenging and Re...,Purpose StatementThe Software Engineering Man...
754,"SummaryHonest, reliable, dependable, hardworki...",56.90,Potential Fit,"SummaryHonest, reliable, dependable, hardworki...",Title Accountant Department Finance Accountin...
81,SummaryElectronics technician and hardware ...,19.42,No Fit,SummaryElectronics technician and hardware ...,Software Data Engineer (ScalaPython) Hybrid o...
1411,SummaryCoordinated Maintenance Electrician at ...,21.00,No Fit,SummaryCoordinated Maintenance Electrician at ...,"Hi, Hope you are doing great today. Please fi..."
3568,"Professional SummaryDependable, results-driven...",21.70,No Fit,"Professional SummaryDependable, results-driven...",( Candidates without any Visa Constraints) ( ...

In [11]:
train["resume"] = train["resume"].apply(clean_text)
train["job_description"] = train["job_description"].apply(clean_text)

valid["resume"] = valid["resume"].apply(clean_text)
valid["job_description"] = valid["job_description"].apply(clean_text)

In [12]:
train.drop(columns=["text"], inplace=True)

valid.drop(columns=["text"], inplace=True)

In [13]:
import re

def preprocess_text(text):

    if pd.isna(text):
        return ""

    text = str(text)

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)

    # Remove HTML
    text = re.sub(r'<.*?>', ' ', text)

    # Add space between letters and numbers
    text = re.sub(r'([a-zA-Z])(\d)', r'\1 \2', text)
    text = re.sub(r'(\d)([a-zA-Z])', r'\1 \2', text)

    # Add space before capital letters in joined words
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)

    # Keep useful symbols
    text = re.sub(r'[^a-z0-9+#.\-\s]', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

In [14]:
train.sample(5)

,ats_score,original_label,resume,job_description
4513,29.5,No Fit,profileskilled motivated and result driven qua...,the position is described below if you want to...
2195,21.3,No Fit,professional summarywith the attitude of learn...,are you passionate about the clean tech automo...
3094,27.3,No Fit,summarydetail oriented with strong skills in r...,we are looking for a cpa with experience worki...
2618,57.7,Potential Fit,summaryquality assurance analyst9 years tandem...,at monument were building a vertical software ...
346,26.5,No Fit,professional backgroundhighly motivated profes...,hello greetings from devcare solutionsi got an...

In [15]:
train["resume"] = train["resume"].apply(preprocess_text)
train["job_description"] = train["job_description"].apply(preprocess_text)

valid["resume"] = valid["resume"].apply(preprocess_text)
valid["job_description"] = valid["job_description"].apply(preprocess_text)

In [16]:
train[["resume","job_description"]].head()

,resume,job_description
0,summaryi am seeking a position wherein i may u...,share resume to shan imrsoft com job title jde...
1,profilehighly motivated sales associate with e...,purpose statementthe software engineering mana...
2,summaryhaving achieved a milestone of 7 years ...,title business analystlocation santa clara ca ...
3,summarywireless communications engineer with e...,job description as a principal software engine...
4,summarydata entry experienced and adept at inp...,title data engineerlocation fully remote howev...

In [17]:
train.head()
train.info()
print(train.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5099 entries, 0 to 5098
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ats_score        5099 non-null   float64
 1   original_label   5099 non-null   object
 2   resume           5099 non-null   object
 3   job_description  5099 non-null   object
dtypes: float64(1), object(3)
memory usage: 159.5+ KB
(5099, 4)

In [18]:
!pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)

In [19]:
pip install sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.4.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.11.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.10.0+cpu)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.24.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.23.0->sentence-transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [20]:
from sentence_transformers import SentenceTransformer